const FedParks = [
  {
    name: "Ebey's Landing National Historical Reserve",
    lat: "48.21403036",
    long: "-122.6877213",
    activities: ["Astronomy", "Biking", "Boating", "Camping", "Hiking"],
    states: "WA",
    url: "https://www.nps.gov/ebla/index.htm",
  },
  {
    name: "Fort Vancouver National Historic Site",
    lat: "45.62234841",
    long: "-122.6617043",
    activities: ["Biking", "Hiking"],
    states: "OR,WA",
    url: "https://www.nps.gov/fova/index.htm",
  },
  {
    name: "Klondike Gold Rush - Seattle Unit National Historical Park",
    lat: "47.5993663",
    long: "-122.3319664",
    activities: ["Walking"],
    states: "WA",
    url: "https://www.nps.gov/klse/index.htm",
  },
  {
    name: "Lake Roosevelt National Recreation Area",
    lat: "48.17148735",
    long: "-118.3513713",
    activities: ["Astronomy", "Boating", "Hiking", "Camping"],
    states: "WA",
    url: "https://www.nps.gov/laro/index.htm",
  },
  {
    name: "Lewis & Clark National Historic Trail",
    lat: "41.2646141052246",
    long: "-95.9245147705078",
    activities: ["Biking", "Fishing", "Hiking"],
    states: "IA,ID,IL,IN,KS,KY,MO,MT,NE,ND,OH,OR,PA,SD,WA,WV",
    url: "https://www.nps.gov/lecl/index.htm",
  },
  {
    name: "Lewis and Clark National Historical Park",
    lat: "46.21178735",
    long: "-123.9638583",
    activities: ["Fishing", "Hiking"],
    states: "OR,WA",
    url: "https://www.nps.gov/lewi/index.htm",
  },
  {
    name: "Minidoka National Historic Site",
    lat: "42.80586068",
    long: "-114.4449868",
    activities: ["Walking"],
    states: "ID,WA",
    url: "https://www.nps.gov/miin/index.htm",
  },
  {
    name: "Mount Rainier National Park",
    lat: "46.86075416",
    long: "-121.7043885",
    activities: [
      "Astronomy",
      "Biking",
      "Hiking",
      "Camping",
      "Climbing",
      "Fishing",
    ],
    states: "WA",
    url: "https://www.nps.gov/mora/index.htm",
  },
  {
    name: "North Cascades National Park",
    lat: "48.71171756",
    long: "-121.2069423",
    activities: ["Biking", "Hiking", "Camping", "Climbing", "Fishing"],
    states: "WA",
    url: "https://www.nps.gov/noca/index.htm",
  },
  {
    name: "Olympic National Park",
    lat: "47.80392754",
    long: "-123.6663848",
    activities: ["Biking", "Hiking", "Camping", "Climbing", "Astronomy"],
    states: "WA",
    url: "https://www.nps.gov/olym/index.htm",
  },
  {
    name: "San Juan Island National Historical Park",
    lat: "48.51241933",
    long: "-123.0610277",
    activities: ["Hiking", "Camping", "Fishing", "Astronomy"],
    states: "WA",
    url: "https://www.nps.gov/sajh/index.htm",
  },
];
module.exports = { FedParks };
